baseURL = "https://www.nuklus.co.za/"
languageCode = "en-us"
title = "Nuklus"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Welcome to Nuklus!"
Content = "All things Telco, Carrier, Service Provider, ISP, and Data Center-related, along with mentorship."

[[params.socialIcons]]
name = "twitter"

[[params.socialIcons]]
name = "github"

[[params.socialIcons]]
name = "linkedin"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

