baseURL = "https://www.nuklus.co.za/"
languageCode = "en-us"
title = "Nuklus"
theme = "PaperMod"

[params.homeInfoParams]
Title = "The Internet is the only network that matters"
Content = "In the words of Dave Schaeffer, CEO of Cogent Communications, the "Internet is the only network that matters.""

[[params.socialIcons]]
name = "twitter"

[[params.socialIcons]]
name = "github"

[[params.socialIcons]]
name = "linkedin"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

